onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /hardnoc_tb/HN/system_clock
add wave -noupdate /hardnoc_tb/HN/system_reset
add wave -noupdate /hardnoc_tb/HN/rxd
add wave -noupdate /hardnoc_tb/HN/txd
add wave -noupdate /hardnoc_tb/HN/reset
add wave -noupdate /hardnoc_tb/HN/ck
add wave -noupdate /hardnoc_tb/HN/locked
add wave -noupdate /hardnoc_tb/HN/start
add wave -noupdate /hardnoc_tb/HN/IP0000/data_out
add wave -noupdate /hardnoc_tb/HN/IP0000/credit_i
add wave -noupdate /hardnoc_tb/HN/IP0000/data_in
add wave -noupdate /hardnoc_tb/HN/IP0000/credit_o
add wave -noupdate /hardnoc_tb/HN/IP0000/ES
add wave -noupdate /hardnoc_tb/HN/IP0000/ER
add wave -noupdate /hardnoc_tb/HN/IP0100/data_out
add wave -noupdate /hardnoc_tb/HN/IP0100/credit_i
add wave -noupdate /hardnoc_tb/HN/IP0100/data_in
add wave -noupdate /hardnoc_tb/HN/IP0100/credit_o
add wave -noupdate /hardnoc_tb/HN/IP0100/ER
add wave -noupdate /hardnoc_tb/HN/IP0100/ES
add wave -noupdate /hardnoc_tb/HN/IP0001/data_out
add wave -noupdate /hardnoc_tb/HN/IP0001/credit_i
add wave -noupdate /hardnoc_tb/HN/IP0001/data_in
add wave -noupdate /hardnoc_tb/HN/IP0001/credit_o
add wave -noupdate /hardnoc_tb/HN/IP0001/ER
add wave -noupdate /hardnoc_tb/HN/IP0001/ES
add wave -noupdate /hardnoc_tb/HN/IP0101/data_out
add wave -noupdate /hardnoc_tb/HN/IP0101/credit_i
add wave -noupdate /hardnoc_tb/HN/IP0101/data_in
add wave -noupdate /hardnoc_tb/HN/IP0101/credit_o
add wave -noupdate /hardnoc_tb/HN/IP0101/ER
add wave -noupdate /hardnoc_tb/HN/IP0101/ES
add wave -noupdate /hardnoc_tb/HN/IP0200/data_out
add wave -noupdate /hardnoc_tb/HN/IP0200/credit_i
add wave -noupdate /hardnoc_tb/HN/IP0200/data_in
add wave -noupdate /hardnoc_tb/HN/IP0200/credit_o
add wave -noupdate /hardnoc_tb/HN/IP0200/ER
add wave -noupdate /hardnoc_tb/HN/IP0200/ES
add wave -noupdate /hardnoc_tb/HN/IP0201/data_out
add wave -noupdate /hardnoc_tb/HN/IP0201/credit_i
add wave -noupdate /hardnoc_tb/HN/IP0201/data_in
add wave -noupdate /hardnoc_tb/HN/IP0201/credit_o
add wave -noupdate /hardnoc_tb/HN/IP0201/ER
add wave -noupdate /hardnoc_tb/HN/IP0201/ES
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {6561352865 ps} 0}
configure wave -namecolwidth 438
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {0 ps} {12728216424 ps}
